### ISSUE TITLE
Half of routes doesn't works

### ISSUE THREAD

**Issue by dobobaie** [rayfranco/aircall#2]
Hello, you need to remove for each routes the default fields : 

```
    from: null, // Set a minimal creation date for objects	(non
    to: null  // Set a maximal creation date for objects
```

But you can keep the others default fields : 
```
    page: 1, // Pagination for list of objects
    per_page: 50, // Number of objects fetched per request
    order: 'asc', // Reorder entries per creation date, asc or desc
```

Because Aircall has changed their apis and `null` (is string type and) is considered like a real field.
Sorry for now I can't published a PR so can you do it ? It will be awesome !

**Comment by tdeschamps** [comment]
Hello, a fix is on the way.
Many thanks for reporting the issue, we will add this case in our test suite in order to prevent this kind of issue to happen again

**Comment by rayfranco** [comment]
Thanks @xdurand for the update, I added the link to the README https://github.com/rayfranco/aircall/commit/a85e0ea03c3d9a5134d799749ee0f19a2c233aa7

@tdeschamps thanks for letting me know. I will close this issue since the fix is on Aircall side. Let me know if any update on this library is needed.
